---
- name: Hello World!
  hosts: all
 
  tasks:
 
  - name: Hello World!
    shell: echo "Hi! Tower is working."
- name: Install helm chart
  helm:
    host: localhost
    chart:
      name: {{ chatr_name }}
      version: {{ version }}
      source:
        type: repo
        location: https://kubernetes-charts.storage.googleapis.com
    state: installed
    name: my-memcached
    namespace: default
